# Generated by Django 3.2.25 on 2024-03-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradingapp_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trading',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
